version: "3"

services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: click2approve
    ports:
      - "3306:3306"
  api:
    container_name: api
    depends_on:
      - db
    build: ./api
    image: luarvic/click2approve-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5555:5555"
    command: /app/wait-for-it.sh -t 60 db:3306 -- dotnet /app/api.dll
  ui:
    container_name: ui
    depends_on:
      - api
    build:
      context: ./ui
      args:
        - ENV=development
    image: luarvic/click2approve-ui:latest
    ports:
      - "3333:3333"
