version: "3"

services:
  db:
    container_name: db
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd
    ports:
      - "1433:1433"
  api:
    container_name: api
    depends_on:
      - db
    build: ./src/api
    image: luarvic/click2approve-api:latest
    ports:
      - "5557:8080"
    command: /app/wait-for-it.sh -t 60 db:1433 -- dotnet /app/api.dll
  ui:
    container_name: ui
    depends_on:
      - api
    build: ./src/ui
    image: luarvic/click2approve-ui:latest
    ports:
      - "80:80"
